name: docker build test

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: goyo9815/server1:${{ steps.commit.outputs.short }}

    outputs:
      commit_hash: ${{ steps.commit.outputs.short }}

      
  argo:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Commit and push generated template
        run: |
          export COMMIT_MESSAGE="Generated template from ${{ needs.docker.outputs.commit_hash }}"
          sed -i 's@goyo9815/server1:.*@goyo9815/server1:${{ needs.docker.outputs.commit_hash }}@g' ./deploy/deployment.yaml
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
